Attempting to fix some of these
BLOODWOLF333/Brutal-Doom-Community-Expansion pull request #414
Opened 2023-02-05 04:42 UTC by DuyGamerLHB

I noticed that you'll sometimes grab an imp outta nowhere and bash his head while attempting to execute a downed zombieman
And attempting to fix some of the enemies spawning different variations when they get interacted (like spamming E on them causes them to change variation when their health reached 0, kind of a weird bug) by making a replacer actor for each of them

2023-02-05 05:47 UTC, BLOODWOLF333 commented
No I dont want those replacers the correct fix is to simply fix the actors spawned in all of their Death.Stealth: states

2023-02-05 06:01 UTC, BLOODWOLF333 commented
No changes need to be made to Player.txt the FinishExecution state of DefaultWeapon.txt needs to be taking away all the execution tokens

2023-02-05 06:01 UTC, BLOODWOLF333 requested changes

2023-02-05 07:25 UTC, DuyGamerLHB commented
Okay so turned out the Stealth thing was caused by their Pain.Stealth or Pain.KillMe state only healing them 1 when the required amount is 2

2023-02-05 09:25 UTC, BLOODWOLF333 commented
and what if on multiplayer multiple players hit an enemy with taunt or stealth attacks they will still go to their death.stealth or death.taunt state.  They either are allowed to just normally die from a fatal hit from a taunt or stealth attack or they spawn a duplicate monster.  Mark chose to make them spawn a duplicate monster *shrugs* either way its silly.

2023-02-05 09:41 UTC, BLOODWOLF333 commented
Player.txt is screwed up

2023-02-05 09:51 UTC, BLOODWOLF333 requested changes

2023-02-05 09:51 UTC, BLOODWOLF333 commented on DEFAULTWEAPON.txt
> +		Goto FinishExecution+6
Goto FinishExecution+6 after the wallbash is going to force the player to look up
FinishExecution:
		TNT1 A 0
		TNT1 AAAAAA(+6)A 1 A_SetPitch(Pitch-10)//+70 deg

2023-02-05 09:51 UTC, BLOODWOLF333 commented on Demons.txt
> +		TNT1 A 0 HealThing(2)
The capturedmarines no longer emit the killme explosions to make other monsters attack them so nothing does that damagetype anymore and the killme states are useless

2023-02-05 09:51 UTC, BLOODWOLF333 commented on Sergeants.txt
> +	Pain.KillMe:
no more killme damagetypes in the game

2023-02-05 09:51 UTC, BLOODWOLF333 commented on Zombiemen.txt
> +		TNT1 A 0
no more killme damagetypes in the game

2023-02-05 10:12 UTC, DuyGamerLHB commented on Zombiemen.txt
> +		TNT1 A 0
oh

2023-02-05 10:24 UTC, DuyGamerLHB commented
I'm just gonna make them die to taunt and stealth normally, because the kill count also got affected by that too

2023-02-05 10:49 UTC, DuyGamerLHB commented
I tried my best on this one

2023-02-05 19:41 UTC, BLOODWOLF333 commented on Baron.txt
>      Death.Taunt:
The belphegor inherits from the baron so since the belphegor doesnt have a Death.killme or taunt state defined it is going to jump back into the baron actor and show a baron death if a belphegor dies from a taunt attack but I can fix that later

2023-02-05 19:43 UTC, BLOODWOLF333 commented on DEFAULTWEAPON.txt
> +		KICK A 0 A_Takeinventory("ExecuteBashWall",1)
this also has to be done for the classic default weapon which I can take care of later

2023-02-05 19:47 UTC, BLOODWOLF333 requested changes
Your doing good, almost done

2023-02-05 19:47 UTC, BLOODWOLF333 commented on Sergeants.txt
> +	    TNT1 A 0 A_ChangeFlag("SOLID", 0)
This needs Goto Death

2023-02-06 07:32 UTC, BLOODWOLF333 approved these changes

2023-02-06 07:33 UTC, merged