Fixing another imperfection & blood drops
BLOODWOLF333/Brutal-Doom-Community-Expansion pull request #429
Opened 2023-05-16 15:06 UTC by DuyGamerLHB

The weird behaviour of the ceiling blood drops, resetting their own vertical velocity, is a bit uncommon but noticeable when you explode or headshot a zombieman on the 4 lifts from the first level in Doom 2, or an enemy on any moving sector. I've been attempting to fix this for days
Plus, I missed the bug where the blasted zombieman will regrow his remains when you gib him after he collapses

2023-05-16 15:14 UTC, DuyGamerLHB commented
By the way, no notated lines this time

2023-05-16 19:31 UTC, BLOODWOLF333 requested changes
I dont see "weird" behavior of the blood dripping from ceiling in-game.  You are going to have to be more specific and detailed because I dont understand what you are talking about with the dripping blood actors.

2023-05-16 19:31 UTC, BLOODWOLF333 commented on Blood.txt
> +		BLUD ZZZZZZZZZZZZZZZZZZZZZZZZZ 20 A_ChangeVelocity(0,0,-1)
What is the point of this?  Just add Live: below the A_Jump(230, "NoSpawn") otherwise when it loops it will jump to the NoSpawn state 230/255% of the time.  The actor is already under the effect of 1.0 gravity so I dont see in-game or how its possible for the drippingblood actor to somehow reset it's velocity.  It can disappear if it exists for more than 500 tics (14.28 seconds) but it's velocity never changes.

2023-05-16 19:31 UTC, BLOODWOLF333 commented on Blood.txt
> +		BLUD ZZZZZZZZZZZZZZZZZZZZZZZZZ 20 A_ChangeVelocity(0,0,-1)
Same here, why?

2023-05-16 19:31 UTC, BLOODWOLF333 commented on Zombiemen.txt
> +		TNT1 A 0 A_SpawnItem ("DeadZombiemanJustLegsAreLeft")
The fix for this should simply be changing A_SpawnItem ("DeadZombieman_NoHeadNoArm") to A_SpawnItem ("DeadZombieman_NoHeadNoArms") so that it doesnt spawn that 3rd arm gib.  Keep things simple dude simple is always better than more complex

2023-05-17 05:29 UTC, DuyGamerLHB commented
> I dont see "weird" behavior of the blood dripping from ceiling in-game. You are going to have to be more specific and detailed because I dont understand what you are talking about with the dripping blood actors.

Idk why but there was a chance that one of the drops stays in one place on certain locations like this one
![Screenshot_Doom_20230517_122033](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/assets/110778501/ecdc63ff-5b8a-4074-ace6-72608bb66c6c)

2023-05-17 05:47 UTC, DuyGamerLHB commented on Zombiemen.txt
> +		TNT1 A 0 A_SpawnItem ("DeadZombiemanJustLegsAreLeft")
> The fix for this should simply be changing A_SpawnItem ("DeadZombieman_NoHeadNoArm") to A_SpawnItem ("DeadZombieman_NoHeadNoArms") so that it doesnt spawn that 3rd arm gib. Keep things simple dude simple is always better than more complex

True. I overcomplicate stuff sometimes, my bad

2023-05-17 15:11 UTC, DuyGamerLHB commented
Hold up, lemme try something else that doesn't accelerate the drops

2023-05-17 23:15 UTC, BLOODWOLF333 commented
Are you sure that blood drop isnt interacting with a gib or weapon pickup spawn?  I dont think there is a problem here and if it is the imp arm or that pistol pickup that is causing the blood drop to stop in mid air that is probably a Doom engine bug and may not be a fix for it.  Would have to update blue and green blood as well anyways.  And I dont want these velocity lines in the dripping blood actors that is not need, they already have a gravity of 1.0 which will constantly accelerate them as they fall they dont need those changevelocity lines I wont accept that.  Dont waste anymore time on the velocity thing.

2023-05-18 04:47 UTC, DuyGamerLHB commented
Okay now I'm starting to think that could have been an engine bug, if I remember correctly, there were also some that didn't interact with anything below but still got frozen

2023-05-18 19:08 UTC, BLOODWOLF333 approved these changes

2023-05-18 19:08 UTC, merged