Changed armless demon's attack
BLOODWOLF333/Brutal-Doom-Community-Expansion pull request #446
Opened 2024-01-02 04:32 UTC by DuyGamerLHB

so that small enemies don't weirdly vanish from thin air and added the vanilla chainsaw sprite

2024-01-02 22:57 UTC, BLOODWOLF333 requested changes
Remove the notation from demon's Death.Taunt state, remove ArmlessDemonAttack actor, change LabGuy's Death.Blast2 state to Death.Eat and that will be good.

2024-01-02 22:57 UTC, BLOODWOLF333 commented on Demons.txt
> +ACTOR ArmlessDemonAttack: DemonAttack
Why does the armless demon need a new attack?

2024-01-02 22:57 UTC, BLOODWOLF333 commented on Demons.txt
> +		Goto Death
Mark has put these catch cases in every monster in case they die from a taunt attack or alerter missile so, leave these lines as is or else every monster file would need to be change to keep them consistent.

2024-01-02 22:57 UTC, BLOODWOLF333 commented on LABGUY.txt
> +	Death.Blast2:
Change this to Death.Eat: to work with the demon fatality

2024-01-03 01:41 UTC, BLOODWOLF333 requested changes

2024-01-03 01:41 UTC, BLOODWOLF333 commented on Demons.txt
> +		TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman")
These dont need to be in the spawn state, like in the parent bulldemon actor it only has these checks in see, when the monster is just idle with no target it doesnt need to be constantly doing these inventory checks and slowing your computer's performance

2024-01-03 01:43 UTC, DuyGamerLHB commented on Demons.txt
> +		TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman")
Oh, I put that in the wrong state, my bad

2024-01-03 01:46 UTC, BLOODWOLF333 approved these changes
GJ

2024-01-03 01:46 UTC, merged